#
# Makefile for studying Linux Devices Driver 3rd.
#

obj-$(CONFIG_MISC_MODULES)	 += complete.o faulty.o hello.o hellop.o jiq.o \
                                jit.o kdataalign.o kdatasize.o seq.o silly.o sleepy.o
